### ISSUE TITLE
smbus2 required -> could be added to setup.py

### ISSUE THREAD

**Issue by avollkopf** [JamFfm/cbpi4-LCDisplay#3]
smbus2 is required for the plugin which is not installed per default. This could be added to the setup.py and would be installed automatically with installation of the plugin.
    ...............
    packages=['LCDisplay'],
	    install_requires=[
            'cbpi>=4.0.0.33',
            'smbus2',
      ],
     ..................

**Comment by JamFfm** [comment]
updated , Thank you very much!!
