### ISSUE TITLE
Kettle Heater Status

### ISSUE THREAD

**Issue by avollkopf** [JamFfm/cbpi4-LCDisplay#4]
Hi, I was browsing your code and found you want to get the status of the kettle heater element.

Assuming you do have a kettle_ID:

```
kettle = self.cbpi.kettle.find_by_id(kettle_ID)
heater = self.cbpi.actor.find_by_id(kettle.heater)
kettle_heater_state = heater.instance.state
```

Regards,
Alex

**Comment by JamFfm** [comment]
Hi, thanks.
I only had a few minutes time to test it. 
Unluckely there is always the same state regardless if the heater(actor) is on or off.
I remember that you claimed this behavior a longer time befor in a different context.
As I said I will have to check more intense and wanted to answer in the meantime.

**Comment by avollkopf** [comment]
No worries. I just figured out that the 'instance.state' instead of 'state' of get('state') is doing the trick. The 'Bierkrug' is now showing on my test system when the heater is on. Interestingly I do not need to define special characters for the Umlauts.

**Comment by JamFfm** [comment]
Hi, yep thats the trick. 
Just for documentation: The code above is working
Thanks again.

**Comment by JamFfm** [comment]
Interesting that Umlaute works without conversion. I guess that the lib is working with Py3 better than py 2. Py 3 uses unicode
